"""
tree_to_seq.py.

Take a file of syntax trees as generated by Noji and Oseki's RNNG code and
convert it into a series of simple sentences.

Expected input:
{"orig_tokens": ["The", "boy", ...], ..., "key": "sentence"}
{"orig_tokens": ["I", "can", ...], ..., "key": "sentence"}
{"orig_tokens": ["If", "you", ...], ..., "key": "sentence"}
...
{"orig_tokens": ["And", ",", ...], ..., "key": "sentence"}
...

Resulting output:
The boy ... <eos>
I can ... <eos>
If you ... <eos>
...
And , ... <eos>

Brighton Pauli
"""
import json


def read_jsonl(filename):
    """Load the given file and yield any jsonl lines with the key "sentence".

    The jsonl format consists of multiple json items (one per line). Each has
    a "key" value which is used to identify which kind of data it contains.

    We want to only extract the dictionaries with the "sentence" key and yield
    them.
    """
    with open(filename, 'r', encoding='utf-8') as file:
        for line in file:
            data = json.loads(line)
            if data['key'] == "sentence":
                yield data
